# https://youtu.be/aIEegP0cUOQ
# yaml file for language and localization support
# the translation files
arb-dir: lib/l10n
# template file
template-arb-file: app_en.arb
# Will autogenerate localization file
output-localization-file: app_localizations.dart
